//INIT MAP
export const INITIAL_MAP = "INITIAL_MAP";

//INFO ADDRESS
export const GET_ADDRESS_REQUEST = "GET_ADDRESS_REQUEST";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_FAILURE = "GET_ADDRESS_FAILURE";

//POINT ADDRESS
export const SELECTED_INFO = "SELECTED_INFO";

//GET DATA MAIN CHART
export const GET_MAIN_CHART_REQUEST = "GET_MAIN_CHART_REQUEST";
export const GET_MAIN_CHART_SUCCESS = "GET_MAIN_CHART_SUCCESS";
export const GET_MAIN_CHART_FAILURE = "GET_MAIN_CHART_FAILURE";

//GET DATA TABLE HOME
export const GET_TABLE_HOME_REQUEST = "GET_TABLE_HOME_REQUEST";
export const GET_TABLE_HOME_SUCCESS = "GET_TABLE_HOME_SUCCESS";
export const GET_TABLE_HOME_FAILURE = "GET_TABLE_HOME_FAILURE";

//GET TOP
export const GET_TOP_REQUEST = "GET_TOP_REQUEST";
export const GET_TOP_SUCCESS = "GET_TOP_SUCCESS";
export const GET_TOP_FAILURE = "GET_TOP_FAILURE";

//GET AREA OF INFLUENCE
export const GET_AREA_INFLUENCE_REQUEST = "GET_AREA_INFLUENCE_REQUEST";
export const GET_AREA_INFLUENCE_SUCCESS = "GET_AREA_INFLUENCE_SUCCESS";
export const GET_AREA_INFLUENCE_FAILURE = "GET_AREA_INFLUENCE_FAILURE";

//GET HOMEZONE WHEEL PLOT
export const GET_HOMEZONE_WHEEL_REQUEST = "GET_HOMEZONE_WHEEL_REQUEST";
export const GET_HOMEZONE_WHEEL_SUCCESS = "GET_HOMEZONE_WHEEL_SUCCESS";
export const GET_HOMEZONE_WHEEL_FAILURE = "GET_HOMEZONE_WHEEL_FAILURE";

