//INIT MAP
export const INITIAL_MAP = "INITIAL_MAP";

//INFO ADDRESS
export const GET_ADDRESS_REQUEST = "GET_ADDRESS";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_FAILURE = "GET_ADDRESS_FAILURE";

//POINT ADDRESS
export const SELECTED_INFO = "SELECTED_INFO";

//GEO DATA
export const GET_GEODATA_REQUEST = "GET_GEODATA";
export const GET_GEODATA_SUCCESS = "GET_GEODATA_SUCCESS";
export const GET_GEODATA_FAILURE = "GET_GEODATA_FAILURE";